public class BillDeskAPIHelper {
    
    public static list<string> fncGetCraditCardInformation(){
        List<string> lstCardDetails=new List<String>();
        
        lstCardDetails.add('4386280029264086');
        lstCardDetails.add('12');
        lstCardDetails.add('2019');
        lstCardDetails.add('***');
        lstCardDetails.add('Devender Singh');
        
        // Card number
       // lstCardDetails.add('43862****9264086');
        //  month    
       // lstCardDetails.add('12');
        //year     
       // lstCardDetails.add('2**9');
        //ccv 
       // lstCardDetails.add('3**');
        //Name 
      //  lstCardDetails.add('Devender Singh');
        return lstCardDetails;
    }
    
}